# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - dev
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
      demands:
      - npm
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - task: CmdLine@2
      displayName: 'npm install and build our cxg_app node api'
      inputs:
        script: |
          npm fund
          npm install
    - task: CmdLine@2
      displayName: 'audit fix'
      inputs:
        script: |
          npm audit fix
          
    - task: Npm@1
      displayName: 'npm version'
      inputs:
        command: 'custom'
        workingDir: $(Build.SourcesDirectory)
        verbose: false
        customCommand: 'version'

    - task: Npm@1
      displayName: npm publish
      inputs:
        command: 'publish'
        publishRegistry: 'useFeed'
        publishFeed: 'CXG-Intern/artifacttest'
        workingDir: '.'
        verbose: true
